---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: arc-runner-set
spec:
  interval: 15m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.8.2
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts
        namespace: flux-system
  maxHistory: 15
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    runnerScaleSetName: test-runners
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/jazzlyn/gh-actions-demo/app-one:rolling@sha256:197532122bb145fc4fdce07b7ef5c7e6731034e684fdb84efee795fb8c75fe04
            command: ["/home/runner/run.sh"]
