---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: arc-runner-set
spec:
  interval: 15m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.8.2
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts
        namespace: flux-system
  maxHistory: 15
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    runnerScaleSetName: test-runners
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/jazzlyn/gh-actions-demo/app-one:dd5d3e4b27a51e11a5b310c3073050d7dbe35734
            command: ["/home/runner/run.sh"]
          - name: runner
            image: ghcr.io/jazzlyn/gh-actions-demo/app-one@sha256:192a47c696a17ce389484d272fe97d192876995bcbd18e217114d1228de09848
            command: ["/home/runner/run.sh"]
          - name: runner
            image: ghcr.io/jazzlyn/gh-actions-demo/app-one:latest@sha256:192a47c696a17ce389484d272fe97d192876995bcbd18e217114d1228de09848
            command: ["/home/runner/run.sh"]
