---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: arc-runner-set
spec:
  interval: 15m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.8.2
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts
        namespace: flux-system
  maxHistory: 15
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    runnerScaleSetName: test-runners
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/strg-at/containers/actions-runner:759e136f7d2731c72e55fa2b0a1d909f83ba3b51
            command: ["/home/runner/run.sh"]
          - name: runner
            image: ghcr.io/strg-at/containers/actions-runner@sha256:e9ab1c8203ed4e93cd4f8c879560a64ce32aafa5b20ac95b00227f50867b5e50
            command: ["/home/runner/run.sh"]
          - name: runner
            image: ghcr.io/strg-at/containers/actions-runner:latest@sha256:e9ab1c8203ed4e93cd4f8c879560a64ce32aafa5b20ac95b00227f50867b5e50
            command: ["/home/runner/run.sh"]
