---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-manifests
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/fluxcd/flux-manifests
  ref:
    # renovate: depName=fluxcd/flux2 datasource=github-releases
    tag: v2.6.3
    digest: sha256:47a5f1919d50a6cbc94cd69a0437332f009a812e7cccf5621dd6ff5477b20b77
