---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-arc
  namespace: flux-system
spec:
  interval: 15m
  path: ./oci/apps/arc/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: dummy
  wait: true
