---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-instance
  namespace: flux-system
spec:
  targetNamespace: flux-system
  path: ./apps/flux-system/flux-instance/app
  prune: false # should never be deleted
  sourceRef:
    kind: OCIRepository
    name: flux-system
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: flux-operator
