---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reloader
  namespace: flux-system
spec:
  targetNamespace: kube-tools
  path: ./kubernetes/apps/kube-tools/reloader/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: dummy
  wait: true
  interval: 15m
  retryInterval: 5s
  timeout: 5m
