---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
spec:
  interval: 15m
  chart:
    spec:
      chart: reloader
      version: 1.0.97
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
  maxHistory: 15
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: "reloader"
    reloader:
      deployment:
        image:
          repository: ghcr.io/stakater/reloader
          tag: v1.0.101@sha256:6909752e7d58638b64991df538fc846776c65e8ab89a4378dc6163f1a55f7e41
