---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
spec:
  interval: 15m
  chart:
    spec:
      chart: reloader
      version: 2.1.3
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
  maxHistory: 15
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: "reloader"
    image:
      repository: ghcr.io/stakater/reloader
      tag: v1.4.4@sha256:a571c5b32c0f0edefdc8c376f585f43e7c8fab59eab57ae5fa2d5ac2f37e0307
