---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
spec:
  interval: 15m
  chart:
    spec:
      chart: reloader
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
  maxHistory: 15
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: "reloader"
    reloader:
      deployment:
        image:
          repository: ghcr.io/stakater/reloader
          tag: v1.1.0@sha256:a6d34801a2b7d38f38a93c72cf8a6a16ceedd510df6c4d25b269bf52b789450a
