---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app test
spec:
  interval: 15m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  # https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    controllers:
      test:
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/strg-at/containers/postgres-db-init
              tag: feb55985ee20c90400dc175d5e8f501a2dc83a37
