# This workflow creates a pr from release/** -> main
---
  name: auto pr
  on:
    workflow_dispatch:
    # push:
    #   branches:
    #     - release/**

  jobs:
    create-pr:
      name: ""
      permissions:
        contents: write
        pull-requests: write
      uses: strg-at/github-workflows/.github/workflows/auto-pr.yaml@bf0a46f1c5ea93006da4145e057ea21aa0d4bffd # v1.5.1
      with:
        runner: '["ubuntu-latest"]'
        branch: main
        update: "true"
        pr-title: "auto-pr: release to main"
