# This workflow creates a pr from release/** -> main
---
  name: auto pr
  on:
    workflow_dispatch:
    # push:
    #   branches:
    #     - release/**

  jobs:
    create-pr:
      name: ""
      permissions:
        contents: write
        pull-requests: write
      uses: strg-at/github-workflows/.github/workflows/auto-pr.yaml@ff86b2cf06e38a4cbc0afaaf0427a9c2549e4a62 # v1.5.2
      with:
        runner: '["ubuntu-latest"]'
        branch: main
        update: "true"
        pr-title: "auto-pr: release to main"
