# This workflow creates a pr from release/** -> main
---
name: auto pr
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - release/**

jobs:
  create-pr:
    name: ""
    permissions:
      contents: write
      pull-requests: write
    uses: strg-at/github-workflows/.github/workflows/auto-pr.yaml@d42227396c7a3608450837821e2ad3b01d0b2301 # v1.8.2
    with:
      runner: '["ubuntu-latest"]'
      branch: main
      update: "true"
      pr-title: "auto-pr: release to main"
