# This workflow creates a pr from release/** -> main
---
name: auto pr
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - release/**

jobs:
  create-pr:
    name: ""
    permissions:
      contents: write
      pull-requests: write
    uses: strg-at/github-workflows/.github/workflows/auto-pr.yaml@ac385260abbb841598c1740ae222d4f1ab3c9b40 # v1.9.0
    with:
      runner: '["ubuntu-latest"]'
      branch: main
      update: "true"
      pr-title: "auto-pr: release to main"
