# This workflow creates a pr from release/** -> main
---
name: auto pr
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - release/**

jobs:
  create-pr:
    name: ""
    permissions:
      contents: write
      pull-requests: write
    uses: strg-at/github-workflows/.github/workflows/auto-pr.yaml@c3b65900e045c388e6895d74522317427453fde0 # v1.6.1
    with:
      runner: '["ubuntu-latest"]'
      branch: main
      update: "true"
      pr-title: "auto-pr: release to main"
