# This workflow creates a pr from release/** -> main
---
name: auto pr
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - release/**

jobs:
  create-pr:
    name: ""
    permissions:
      contents: write
      pull-requests: write
    uses: strg-at/github-workflows/.github/workflows/auto-pr.yaml@24d79a482f0d30cef0cfc87f97183ec42559d29b # v1.7.1
    with:
      runner: '["ubuntu-latest"]'
      branch: main
      update: "true"
      pr-title: "auto-pr: release to main"
