---
name: cluster dispatch

on:
  repository_dispatch:
    types:
      - integration-dispatch
      - staging-dispatch
      - production-dispatch

jobs:

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

  integration-dispatch:
    if: ${{ github.event_name == 'integration-dispatch' }}
    uses: "strg-at/github-workflows/.github/workflows/repo-dispatch.yaml@v0.4.0"
    with:
      runner: '["ubuntu-latest"]'
      sha: ${{ github.event.client_payload.sha }}
      repository: jazzlyn/gh-actions-demo
      dispatch-event: app-integration-tag-update
    secrets:
      github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
      github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

  staging-dispatch:
    if: ${{ github.event_name == 'staging-dispatch' }}
    uses: "strg-at/github-workflows/.github/workflows/repo-dispatch.yaml@v0.4.0"
    with:
      runner: '["ubuntu-latest"]'
      sha: ${{ github.event.client_payload.sha }}
      repository: jazzlyn/gh-actions-demo
      dispatch-event: app-staging-tag-update
    secrets:
      github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
      github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

  production-dispatch:
    if: ${{ github.event_name == 'production-dispatch' }}
    uses: "strg-at/github-workflows/.github/workflows/repo-dispatch.yaml@v0.4.0"
    with:
      runner: '["ubuntu-latest"]'
      sha: ${{ github.event.client_payload.sha }}
      repository: jazzlyn/gh-actions-demo
      dispatch-event: app-production-tag-update
    secrets:
      github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
      github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}
