---
name: build and push docker image

on:
  workflow_dispatch:
    inputs:
      image:
        description: "image name"
        required: true
        type: string
      context:
        description: "path to Dockerfile"
        required: true
        type: string

jobs:
  docker-build-push:
    uses: "strg-at/github-workflows/.github/workflows/docker-build-push-github.yaml@feature/AGENTS-957-docker-build-push-github"
    with:
      runner: home-infra
      image: ${{ inputs.image }}
      context: ${{ inputs.context }}
