---
name: docker-build-push-tag

on:
  push:
    tags:
      - "v*.*.*"
      - "*.*.*"

jobs:
  docker-build-push:
    uses: techtales-io/github-workflows/.github/workflows/docker-push.yaml@087a877c5029965026268769fbabe16cc00d76f4 # v0.5.5
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      runner: ubuntu-latest
      tags: |
        type=ref,event=tag,priority=300
        ${{ github.sha }}
        type=raw, value=rolling
