---
name: docker-build-push-tag

on:
  push:
    tags:
      - "v*.*.*"
      - "*.*.*"

jobs:
  docker-build-push:
    uses: techtales-io/github-workflows/.github/workflows/docker-push.yaml@126f6d2dadca32e3031693f223f08df897adf2d3 # v0.5.6
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      runner: ubuntu-latest
      tags: |
        type=ref,event=tag,priority=300
        ${{ github.sha }}
        type=raw, value=rolling
