---
name: docker-build-push

on:
  workflow_dispatch:
    inputs:
      path:
        description: "path to directory containing the Dockerfile file, f.e. app-one"
        required: true
        type: string

jobs:
  docker-build-push:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: strg-at/github-workflows/.github/workflows/docker-build-push-github.yaml@d9e34d0592a67b766a2d105af8cc1fc5e825861e # v1.6.0
    with:
      runner: '["ubuntu-latest"]'
      subpath: ${{ inputs.path }}
      file: ${{ inputs.path }}/Dockerfile
      context: ${{ inputs.path }}
      tags: |
        ${{ github.sha }}
        type=raw, value=rolling


# jobs:
#   docker-build-push-github:
#     name: github
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       id-token: write
#       packages: write
#     env:
#       image-path: ghcr.io/${{ github.repository }}/${{ inputs.subpath }}
#     outputs:
#       metadata: ${{ steps.meta.outputs.json }}

#     steps:
#       # https://github.com/marketplace/actions/checkout
#       - name: checkout repository
#         uses: actions/checkout@v4.1.1

#       # https://github.com/marketplace/actions/cosign-installer
#       - name: setup cosign
#         uses: sigstore/cosign-installer@v3.4.0

#       # Workaround: https://github.com/docker/build-push-action/issues/461
#       # https://github.com/marketplace/actions/docker-setup-qemu
#       - name: setup QEMU
#         uses: docker/setup-qemu-action@v3.0.0

#       # https://github.com/marketplace/actions/docker-setup-buildx
#       - name: setup docker buildx
#         uses: docker/setup-buildx-action@v3.0.0

#       # https://github.com/marketplace/actions/docker-login
#       - name: log into registry
#         uses: docker/login-action@v3.0.0
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       # https://github.com/marketplace/actions/docker-metadata-action
#       - name: extract metadata for docker
#         id: meta
#         uses: docker/metadata-action@v5.5.1
#         with:
#           images: ${{ env.image-path }}
#           tags: |
#             ${{ github.sha }}
#             type=raw, value=rolling

#       # https://github.com/marketplace/actions/build-and-push-docker-images
#       - name: build and push docker image
#         id: build-and-push
#         uses: docker/build-push-action@v5.1.0
#         with:
#           push: true
#           file: ${{ inputs.subpath }}/Dockerfile
#           context: ${{ inputs.subpath }}
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}

#       # https://github.com/sigstore/cosign
#       - name: sign the published docker image
#         run: cosign sign --yes ${{ env.image-path }}@${{ steps.build-and-push.outputs.digest }}
