---
name: docker-build-push

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: "multi-platform images"
        required: false
        type: string

jobs:
  docker-build-push:
    uses: "strg-at/github-workflows/.github/workflows/docker-build-push-github.yaml@95c9aa14d3d09c074b0f569492daee068eb972e8"
    with:
      runner: '["ubuntu-latest"]'
      subpath: nginx
      platforms: ${{ inputs.platforms }}
