---
name: docker-build-push-tag

on:
  push:
    tags:
      - "v*.*.*"
      - "*.*.*"

jobs:
  docker-build-push:
    uses: techtales-io/github-workflows/.github/workflows/docker-push.yaml@2e6bcf9acd97ef3bc52ee0e4919656add4dc45ef # v0.5.7
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      runner: ubuntu-latest
      tags: |
        type=ref,event=tag,priority=300
        ${{ github.sha }}
        type=raw, value=rolling
