---
name: build and push docker image

on:
  workflow_dispatch:
    inputs:
      context:
        description: "app folder with Dockerfile"
        required: true
        type: string

jobs:
  docker-build-push:
    uses: "strg-at/github-workflows/.github/workflows/docker-build-push-github.yaml@feature/AGENTS-957-docker-build-push-github"
    with:
      runner: '["ubuntu-latest"]'
      image: ${{ inputs.context }}
      context: ${{ inputs.context }}
