---
name: build and push docker image

on:
  workflow_dispatch:

jobs:
  docker-build-push:
    uses: "strg-at/github-workflows/.github/workflows/docker-build-push-github.yaml@feature/GC-1078-setup-multi-environment-ci"
    with:
      runner: '["ubuntu-latest"]'
      subpath: nginx
      tags: |
        type=sha,prefix={{date 'YYMMDD-HHmmss'}}-,priority=200
        ${{ github.sha }}, priority=100

  repo-dispatch:
    needs: [docker-build-push]
    name: dispatch
    uses: "strg-at/github-workflows/.github/workflows/repo-dispatch.yaml@feature/GC-1078-setup-multi-environment-ci"
    with:
      runner: '["ubuntu-latest"]'
      sha: ${{ fromJSON(needs.docker-build-push.outputs.metadata).labels['org.opencontainers.image.version'] }}
      repository: jazzlyn/gh-actions-demo
      dispatch-event: dispatch-test-app
    secrets:
      github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
      github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}
