---
name: docker-build-push

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: "multi-platform images"
        required: false
        type: string

jobs:
  docker-build-push:
    uses: "strg-at/github-workflows/.github/workflows/docker-build-push-github.yaml@8154d53d25773fc9aba1ffb5cbbfea6ad4302c91"
    with:
      runner: '["ubuntu-latest"]'
      subpath: nginx
      platforms: ${{ inputs.platforms }}
