---
name: docker-build

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - .github/**

jobs:
  docker-build:
    permissions:
      contents: read
      packages: read
    uses: strg-at/github-workflows/.github/workflows/docker-build.yaml@ee3733899572f6a1de4a2b467e854bb0b2882674 # v2.0.0
    with:
      runner: '["ubuntu-latest"]'
    # secrets:
    #   docker-username: ${{ secrets.DOCKER_USERNAME }}
    #   docker-token: ${{ secrets.DOCKER_TOKEN }}
