---
name: build and push docker image

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*

jobs:
  file:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: create file
        run: |
          echo "hello world" > $GITHUB_WORKSPACE/hello.txt
          ls -la
          pwd

  docker-build:
    runs-on: ubuntu-latest
    needs: [file]
    permissions:
      contents: read
    steps:
      - name: ls
        run: |
          ls -la $GITHUB_WORKSPACE
          pwd
      # Workaround: https://github.com/docker/build-push-action/issues/461
      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: setup QEMU
        uses: docker/setup-qemu-action@v2.1.0

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          driver: docker

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: build docker image
        uses: docker/build-push-action@v4.0.0
        with:
          push: false
          tags: ${{ github.sha }}

      - name: ls
        run: |
          ls -la
          pwd

  ls:
    needs: [file, docker-build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: ls
        run: |
          ls -la $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          pwd
