---
name: docker-build-push

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: "multi-platform images"
        required: false
        type: string

jobs:
  docker-build-push:
    uses: "strg-at/github-workflows/.github/workflows/docker-build-push-github.yaml@feature/INPRO-1618-multi-platform-images"
    with:
      runner: '["ubuntu-latest"]'
      subpath: test-image
      platforms: ${{ inputs.platforms }}
