---
name: docker-build

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - .github/**

jobs:
  docker-build:
    permissions:
      contents: read
      packages: read
    uses: strg-at/github-workflows/.github/workflows/docker-build.yaml@ae16851644aa20761762716e874cebdf811fbd40 # v2.1.4
    with:
      runner: '["ubuntu-latest"]'
    # secrets:
    #   docker-username: ${{ secrets.DOCKER_USERNAME }}
    #   docker-token: ${{ secrets.DOCKER_TOKEN }}
