---
name: docker-build-push

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: "multi-platform images"
        required: false
        type: string

jobs:
  docker-build-push:
    uses: "strg-at/github-workflows/.github/workflows/docker-build-push-github.yaml@d0b83dc8394a3ec557b374e942bd3610a3ad13b6"
    with:
      runner: '["ubuntu-latest"]'
      subpath: nginx
      platforms: ${{ inputs.platforms }}
