---
name: docker-build-push

on:
  workflow_dispatch:
    inputs:
      path:
        description: "path to directory containing the Dockerfile file, f.e. app-one"
        required: true
        type: string
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "*/**"
  #     - "!.github/**"

jobs:
  get-changed-files:
    if: github.event_name == 'push'
    permissions:
      contents: read
    uses: strg-at/github-workflows/.github/workflows/get-changed-files.yaml@2c66a1785479e7c2a17dd28b872dad7a4c85567c
    with:
      runner: '["ubuntu-latest"]'
      files: |
        **/*
      matrix: true
      dir_names: true

  docker-build-push:
    needs: [get-changed-files]
    if: ${{ always() && (github.event_name == 'workflow_dispatch' || needs.get-changed-files.result == 'success') }}
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      matrix:
        path: ${{ github.event_name == 'push' && fromJSON(needs.get-changed-files.outputs.files) || fromJSON('[""]') }}
    uses: strg-at/github-workflows/.github/workflows/docker-build-push-github.yaml@2c66a1785479e7c2a17dd28b872dad7a4c85567c
    with:
      runner: '["ubuntu-latest"]'
      subpath: ${{ github.event_name == 'workflow_dispatch' && inputs.path || matrix.path }}
      file: ${{ github.event_name == 'workflow_dispatch' && format('{0}/Dockerfile', inputs.path) || format('{0}/Dockerfile', matrix.path) }}
      context: ${{ github.event_name == 'workflow_dispatch' && inputs.path || matrix.path }}
      tags: |
        ${{ github.sha }}
        type=raw, value=rolling
