---
name: docker-build-push

on:
  workflow_dispatch:
    inputs:
      subpath:
        description: "path to directory containing the Dockerfile file, f.e. postgres-db-init"
        required: true
        type: string

jobs:
  docker-build-push-github:
    name: github
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    env:
      image-path: ghcr.io/${{ github.repository }}/${{ inputs.subpath }}
    outputs:
      metadata: ${{ steps.meta.outputs.json }}

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # https://github.com/marketplace/actions/cosign-installer
      - name: setup cosign
        uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4 # v3.4.0

      # Workaround: https://github.com/docker/build-push-action/issues/461
      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: setup docker buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # https://github.com/marketplace/actions/docker-login
      - name: log into registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/marketplace/actions/docker-metadata-action
      - name: extract metadata for docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ${{ env.image-path }}
          tags: |
            ${{ github.sha }}
            type=raw, value=rolling

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: build and push docker image
        id: build-and-push
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          push: true
          file: ${{ inputs.subpath }}/Dockerfile
          context: ${{ inputs.subpath }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # https://github.com/sigstore/cosign
      - name: sign the published docker image
        run: cosign sign --yes ${{ env.image-path }}@${{ steps.build-and-push.outputs.digest }}
