---
name: build and push docker image

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*

jobs:
  file:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: create file
        run: |
          echo "hello world" > hello.txt

  docker-build-push:
    uses: "strg-at/github-workflows/.github/workflows/docker-build-push-github.yaml@v0.6.0"
    with:
      runner: '["ubuntu-latest"]'
      subpath: nginx
      tags: |
        type=ref,event=tag,priority=300
        type=sha,prefix={{date 'YYMMDD-HHmmss'}}-,priority=200
        ${{ github.sha }}, priority=100

  ls:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: ls
        run: |
          ls -la
