---
name: docker-build

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - .github/**

jobs:
  docker-build:
    permissions:
      contents: read
      packages: read
    uses: strg-at/github-workflows/.github/workflows/docker-build.yaml@2c2ab5cac48aa7c90d103cd6552ca5ef013cad81 # v2.4.0
    with:
      runner: '["ubuntu-latest"]'
    # secrets:
    #   docker-username: ${{ secrets.DOCKER_USERNAME }}
    #   docker-token: ${{ secrets.DOCKER_TOKEN }}
