---
name: multi-tag-update

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag, f.e. github.sha"
        required: true
        type: string
      tag-path:
        description: "tag-path in yaml, f.e. .spec.values.image.tag"
        required: false
        type: string
        default: ".spec.values.image.tag"
      file-path:
        description: "file-path, f.e. tag-update/testfile.yaml"
        required: true
        type: string
      create-pr:
        description: "create pr, boolean"
        required: false
        type: boolean
        default: true
      branch-name:
        description: "branch-name, f.e. release/update-image"
        required: false
        type: string
        default: "release/update-image"
      destination-branch:
        description: "destination-branch, f.e. main"
        required: false
        type: string
        default: main
      pr-title:
        description: "pr-title, f.e. release: tag"
        required: false
        type: string
        default: "automated pr for updating image tag"
      pr-body:
        description: "pr-body, default empty"
        required: false
        type: string
        default: ""
      commit-message:
        description: "commit-message, f.e. release: tag"
        required: false
        type: string
        default: "chore: update"

jobs:
  tag-update:
    name: tag-update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@v4.1.1

      # https://github.com/marketplace/actions/setup-yq
      - name: update image tag of release
        uses: mikefarah/yq@v4.35.2
        with:
          cmd: yq -i '${{ inputs.tag-path }} = "${{ inputs.tag }}"' ${{ inputs.file-path }}

      # https://github.com/marketplace/actions/github-app-token
      - name: generate token
        id: generate-token
        uses: tibdex/github-app-token@v2.1.0
        env:
          # https://github.com/tibdex/github-app-token/issues/54
          # https://stackoverflow.com/questions/72104449/node-js-crypto-fails-to-sign-pem-key-string-from-file-with-error25066067dso-su
          OPENSSL_CONF: /dev/null
        with:
          app_id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
          private_key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

      - name: ensure branch does not exist
        if: ${{ inputs.create-pr }}
        id: branch-does-not-exist
        run: |
          curl -I \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/branches/${{ inputs.branch-name }} | grep "HTTP/2 404"

      # https://github.com/marketplace/actions/create-branch
      - name: create branch
        id: create-branch
        if: ${{ inputs.create-pr }} && steps.branch-does-not-exist.outcome == 'success'
        uses: peterjgrainger/action-create-branch@v2.4.0
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          branch: refs/heads/${{ inputs.branch-name }}
          sha: ${{ github.sha }}

      # https://github.com/marketplace/actions/multi-file-commit
      - name: multi-file-commit
        id: multi-file-commit
        uses: tyriis/multi-file-commit@v0.3.11
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: ${{ inputs.branch-name || github.ref_name }}
          message: ${{ inputs.commit-message }}

      # https://github.com/marketplace/actions/pull-request-action
      - name: create pr
        if: ${{ inputs.create-pr }}
        uses: vsoch/pull-request-action@1.1.0
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          PULL_REQUEST_BRANCH: ${{ inputs.destination-branch }}
          PULL_REQUEST_FROM_BRANCH: ${{ inputs.branch-name }}
          PULL_REQUEST_TITLE: ${{ inputs.pr-title }}
          PULL_REQUEST_BODY: ${{ inputs.pr-body }}
          PULL_REQUEST_UPDATE: "true"
