---
name: multi-tag-update

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "f.e. github.sha"
        required: true
        type: string
      file-path:
        description: "tag-update/testfile.yaml"
        required: true
        type: string
      branch-name:
        description: "release/tag"
        required: false
        type: string
        default: "release/update-helm-image"
      destination-branch:
        description: "main"
        required: false
        type: string
        default: main
      pr-title:
        description: "release: tag"
        required: false
        type: string
        default: "automated pr for updating helm image"
      commit-message:
        description: "release: tag"
        required: false
        type: string
        default: "chore: update"

jobs:
  tag-update-helm:
    name: helm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@v3.6.0

      # https://github.com/marketplace/actions/install-gh-cli
      - name: install github cli
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      # https://github.com/marketplace/actions/setup-yq
      - name: update image tag of helm-release
        uses: mikefarah/yq@v4.35.2
        with:
          cmd: yq -i '.spec.values.image.tag = "${{ inputs.tag }}"' ${{ inputs.file-path }}

      # https://github.com/marketplace/actions/github-app-token
      - name: generate token
        id: generate-token
        uses: tibdex/github-app-token@v2.1.0
        env:
          # https://github.com/tibdex/github-app-token/issues/54
          # https://stackoverflow.com/questions/72104449/node-js-crypto-fails-to-sign-pem-key-string-from-file-with-error25066067dso-su
          OPENSSL_CONF: /dev/null
        with:
          app_id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
          private_key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

      # https://github.com/marketplace/actions/create-branch
      - name: create branch
        uses: peterjgrainger/action-create-branch@v2.4.0
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          branch: refs/heads/${{ inputs.branch-name }}
          sha: ${{ github.sha }}

      # https://github.com/marketplace/actions/multi-file-commit
      - name: multi-file-commit
        id: multi-file-commit
        uses: tyriis/multi-file-commit@v0.3.11
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: ${{ inputs.branch-name }}
          message: ${{ inputs.commit-message }}

      - name: create pr
        uses: vsoch/pull-request-action@1.0.24
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          PULL_REQUEST_BRANCH: main
          PULL_REQUEST_FROM_BRANCH: ${{ inputs.branch-name }}
          PULL_REQUEST_TITLE: ${{ inputs.pr-title }}
          PULL_REQUEST_UPDATE: "true"
