---
name: renovate

on:
  workflow_dispatch:
    inputs:
      log-level:
        description: "log-level (debug, info, warn, error, fatal)"
        required: false
        type: string
        default: "debug"
      dry-run:
        description: "dry-run (extract, lookup, full)"
        required: false
        type: string
        default: "null"
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/renovate-bot.json5
      - .github/renovate/**.json5
      - .github/workflows/renovate.yaml

concurrency:
  group: renovate
  cancel-in-progress: true

# jobs:
#   renovate:
#     uses: strg-at/github-workflows/.github/workflows/run-renovate.yaml@c1b31ff6c2d848b014596b6f919336d6ae89d8de # v1.9.1
#     permissions:
#       contents: read
#     with:
#       runner: '["ubuntu-latest"]'
#       configuration-file: .github/renovate-bot.json5
#       dry-run: ${{ inputs.dry-run || 'null' }}
#       log-level: ${{ inputs.log-level || 'debug' }}
#     secrets:
#       github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
#       github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}
jobs:
  renovate:
    runs-on: arc-runner-set-gh-actions-demo
    permissions:
      contents: read
      id-token: write
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: generate token
        id: generate-token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        with:
          app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.generate-token.outputs.token }}

      # https://github.com/marketplace/actions/renovate-bot-github-action
      - name: renovate bot
        uses: renovatebot/github-action@0984fb80fc633b17e57f3e8b6c007fe0dc3e0d62 # v40.3.6
        env:
          LOG_LEVEL: ${{ inputs.log-level || 'info' }}
          RENOVATE_DRY_RUN: ${{ inputs.dry-run || 'null' }}
        with:
          token: ${{ steps.generate-token.outputs.token }}
          configurationFile: .github/renovate-bot.json5
