---
name: renovate

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: dry run mode
        type: choice
        options:
          - "null"
          - extract
          - lookup
          - full
        default: "null"
        required: false
      log-level:
        description: renovate log level
        type: choice
        options:
          - debug
          - info
          - warn
          - error
          - fatal
        default: debug
        required: false
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/renovate-bot.json5
      - .github/renovate/**.json5
      - .github/workflows/renovate.yaml

concurrency:
  group: renovate
  cancel-in-progress: true

# jobs:
#   renovate:
#     uses: strg-at/github-workflows/.github/workflows/run-renovate.yaml@c1b31ff6c2d848b014596b6f919336d6ae89d8de # v1.9.1
#     permissions:
#       contents: read
#     with:
#       runner: '["ubuntu-latest"]'
#       configuration-file: .github/renovate-bot.json5
#       dry-run: ${{ inputs.dry-run || 'null' }}
#       log-level: ${{ inputs.log-level || 'debug' }}
#     secrets:
#       github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
#       github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}
jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: generate token
        id: generate-token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        with:
          app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ steps.generate-token.outputs.token }}

      # https://github.com/marketplace/actions/renovate-bot-github-action
      - name: renovate bot
        uses: renovatebot/github-action@9ba84f1ade243f8c2ce5b223df61cf23dc094584 # v43.0.13
        env:
          LOG_LEVEL: ${{ inputs.log-level || 'debug' }}
          RENOVATE_CONFIG_FILE: .github/renovate-bot.json5
          RENOVATE_DRY_RUN: ${{ inputs.dry-run || 'null' }}
          RENOVATE_TOKEN: ${{ steps.generate-token.outputs.token }}
