---
name: renovate

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: dry-run
        required: false
        type: string
        default: "false"
      log-level:
        description: log-level
        required: false
        type: string
        default: info
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/renovate/**.json5
      - .github/workflows/renovate.yaml

concurrency:
  group: renovate
  cancel-in-progress: true

# jobs:
#   renovate:
#     uses: strg-at/github-workflows/.github/workflows/run-renovate.yaml@v1.5.1
#     permissions:
#       contents: read
#       id-token: write
#     with:
#       runner: '["ubuntu-latest"]'
#       configuration-file: .github/renovate-bot.json5
#       dry-run: ${{ inputs.dry-run || 'false' }}
#       log-level: ${{ inputs.log-level || 'info' }}
#     secrets:
#       github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
#       github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: generate token
        id: generate-token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        with:
          app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ steps.generate-token.outputs.token }}

      # https://github.com/marketplace/actions/renovate-bot-github-action
      - name: renovate bot
        uses: renovatebot/github-action@76d49712364696a06b60e8647df46b288fff0ddc # v40.2.4
        env:
          DRY_RUN: ${{ inputs.dry-run || 'false' }}
          LOG_LEVEL: ${{ inputs.log-level || 'info' }}
          # DOCKER_EUROPE__WEST3__DOCKER_PKG_DEV_TOKEN: ${{ steps.auth.outputs.access_token }}
        with:
          token: ${{ steps.generate-token.outputs.token }}
          configurationFile: .github/renovate-bot.json5
