---
name: renovate

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: dry-run
        required: false
        type: string
        default: "false"
      log-level:
        description: log-level
        required: false
        type: string
        default: info
  # schedule:
  #   - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/renovate/**.json5
      - .github/workflows/renovate.yaml

concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    uses: strg-at/github-workflows/.github/workflows/run-renovate.yaml@feature/INPRO-2044-setup-artifact-auth-renovate
    permissions:
      contents: read
      id-token: write
    with:
      runner: '["arc-runner-set-gh-actions-demo"]'
      configuration-file: .github/renovate-bot.json5
      dry-run: ${{ inputs.dry-run || 'false' }}
      log-level: ${{ inputs.log-level || 'info' }}
    secrets:
      github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
      github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

# jobs:
#   renovate:
#     runs-on: ubuntu-latest
#     steps:
#       - name: generate Token
#         uses: tibdex/github-app-token@v2.1.0
#         id: generate-token
#         with:
#           app_id:  ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
#           private_key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

#       # https://github.com/marketplace/actions/checkout
#       - name: Checkout
#         uses: actions/checkout@v4.1.1
#         with:
#           token: "${{ steps.generate-token.outputs.token }}"

#       # https://github.com/marketplace/actions/renovate-bot-github-action
#       - name: Renovate
#         uses: renovatebot/github-action@v40.1.2
#         with:
#           configurationFile: .github/renovate-bot.json5
#           token: "${{ steps.generate-token.outputs.token }}"
