---
name: renovate

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: dry-run
        required: false
        type: string
        default: "false"
      log-level:
        description: log-level
        required: false
        type: string
        default: info
  # schedule:
  #   - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/renovate/**.json5
      - .github/workflows/renovate.yaml

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: generate Token
        uses: tibdex/github-app-token@v1.8.0
        id: generate-token
        with:
          app_id:  ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
          private_key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3.5.0
        with:
          token: "${{ steps.generate-token.outputs.token }}"

      # https://github.com/marketplace/actions/renovate-bot-github-action
      - name: Renovate
        uses: renovatebot/github-action@v40.0.2
        with:
          configurationFile: .github/renovate-bot.json5
          token: "${{ steps.generate-token.outputs.token }}"
