---
name: repo-dispatch

on:
  workflow_dispatch:
  # workflow_call:
  #   inputs:
  #     runner:
  #       description: '["some-runners"]'
  #       required: true
  #       type: string
  #     tag:
  #       description: "version tag from docker metadata"
  #       required: false
  #       type: string
  #       default: null
  #     repository:
  #       description: "target repository"
  #       required: true
  #       type: string
  #     dispatch-event:
  #       description: "event name that is configured in target repo"
  #       required: true
  #       type: string
  #   secrets:
  #     github-app-id:
  #       description: "github app id"
  #       required: true
  #     github-app-key:
  #       description: "github app private key"
  #       required: true

# jobs:
#   test-dispatch:
#     uses: strg-at/github-workflows/.github/workflows/repo-dispatch.yaml@bugfix/INPRO-2388-fix-repo-dispatch
#     with:
#       runner: '["ubuntu-latest"]'
#       tag: ${{ github.sha }}
#       repository: jazzlyn/kind-flux-demo
#       repository-owner: jazzlyn
#       dispatch-event: test-dispatch
#     secrets:
#       github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
#       github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

jobs:
  repo-dispatch:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: generate token
        id: generate-token
        uses: actions/create-github-app-token@v1.10.3
        with:
          app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}
          owner: ${{ github.repository_owner }}

      # send event to remote repo to update helm-release image tag
      # https://github.com/marketplace/actions/repository-dispatch
      - name: repository dispatch
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570 # v2.1.2
        env:
          token: ${{ steps.generate-token.outputs.token }}
          tag: ${{ github.sha }}
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: jazzlyn/kind-flux-demo
          event-type: test-dispatch
          client-payload: '{"ref": "${{ github.ref }}", "tag": "${{ github.sha }}"}'
