---
name: tag-update

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - integration-nginx
      # - staging-nginx

jobs:
  integration-tag-update-backend:
    if: ${{ github.event.action == 'integration-nginx' }}
    uses: "strg-at/github-workflows/.github/workflows/value-updater-yaml.yaml@main"
    with:
      runner: '["ubuntu-latest"]'
      value: ${{ github.event.client_payload.tag }}
      value-path: .app.backend.code
      file-path: versions/integration.yaml
      create-pr: false
      commit-branch: main
      commit-message: "release(backend): update integration to ${{ github.event.client_payload.tag }}"
    secrets:
      github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
      github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

  integration-tag-update-frontend:
    if: ${{ github.event.action == 'integration-nginx' }}
    uses: "strg-at/github-workflows/.github/workflows/value-updater-yaml.yaml@main"
    with:
      runner: '["ubuntu-latest"]'
      value: ${{ github.event.client_payload.tag }}
      value-path: .app.frontend.code
      file-path: versions/integration.yaml
      create-pr: false
      commit-branch: main
      commit-message: "release(frontend): update integration to ${{ github.event.client_payload.tag }}"
    secrets:
      github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
      github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

  integration-tag-update-api:
    if: ${{ github.event.action == 'integration-nginx' }}
    uses: "strg-at/github-workflows/.github/workflows/value-updater-yaml.yaml@main"
    with:
      runner: '["ubuntu-latest"]'
      value: ${{ github.event.client_payload.tag }}
      value-path: .app.api.code
      file-path: versions/integration.yaml
      create-pr: false
      commit-branch: main
      commit-message: "release(api): update integration to ${{ github.event.client_payload.tag }}"
    secrets:
      github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
      github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}
