---
name: tag-update

on:
  repository_dispatch:
    types: [integration-nginx]

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: |
          echo '${{ toJSON(github) }}'
          echo '${{ github.triggering_actor }}'
          echo '${{ github.actor }}'
  tag-update:
    if: ${{ github.event.action == 'integration-nginx' }}
    uses: "strg-at/github-workflows/.github/workflows/tag-update-helm-image.yaml@d3bf14987cb76d8b94fa7e7a1f146029f243e23f"
    with:
      runner: '["ubuntu-latest"]'
      tag: ${{ github.event.client_payload.tag }}
      file-path: tag-update/testfile.yaml
      create-pr: false
    secrets:
      github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
      github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}
