---
name: test-php

on:
  workflow_dispatch:

jobs:
  test-php:
    name: test
    uses: "strg-at/github-workflows/.github/workflows/test-php.yaml@3d7b59957f65c08a3e2b5d3228ee3744bbcb72a7" # v2.1.9
    with:
      runner: '["ubuntu-latest"]'
      php-lint: true
      php-cs-fixer: true
      php-stan: true
      php-stan-cmd: analyse test-php/
