---
name: test-php

on:
  workflow_dispatch:

jobs:
  test-php:
    name: test
    uses: "strg-at/github-workflows/.github/workflows/test-php.yaml@ae16851644aa20761762716e874cebdf811fbd40" # v2.1.4
    with:
      runner: '["ubuntu-latest"]'
      php-lint: true
      php-cs-fixer: true
      php-stan: true
      php-stan-cmd: analyse test-php/
