---
name: test-php

on:
  workflow_dispatch:

jobs:
  test-php:
    name: test
    uses: "strg-at/github-workflows/.github/workflows/test-php.yaml@948a59ecdf5297443483028e7c627d1afca14d7d" # v2.3.0
    with:
      runner: '["ubuntu-latest"]'
      php-lint: true
      php-cs-fixer: true
      php-stan: true
      php-stan-cmd: analyse test-php/
