---
name: version-bump

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'semantic version bump type (major minor patch)'
        required: true

concurrency: # prevent concurrent releases
  group: version-bump
  cancel-in-progress: true

jobs:
  version-bump:
    runs-on:
      - self-hosted
      - home-infra
    permissions:
      contents: write
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@v3.5.0

      # # https://github.com/marketplace/actions/setup-node-js-environment
      # - name: setup node.js
      #   uses: actions/setup-node@v3.6.0
      #   with:
      #     node-version-file: .nvmrc
      #     cache: npm

      # https://github.com/marketplace/actions/github-app-token
      - name: generate token
        id: generate-token
        uses: tibdex/github-app-token@v1.8.0
        env:
          # https://github.com/tibdex/github-app-token/issues/54
          # https://stackoverflow.com/questions/72104449/node-js-crypto-fails-to-sign-pem-key-string-from-file-with-error25066067dso-su
          OPENSSL_CONF: /dev/null
        with:
          app_id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
          private_key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

      - name: npm version bump
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          version-type: ${{ inputs.version }}
          tag-prefix:  'v'
          commit-message: 'release: {{ version }}'
          minor-wording:  'minor'
          major-wording:  'major'
          patch-wording:  'patch'
          rc-wording:     'alpha'
