---
name: npm version bump

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'semantic version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          # - major

concurrency:
  group: npm-version-bump
  cancel-in-progress: true

jobs:
  npm-version-bump:
    name: ""
    uses: "strg-at/github-workflows/.github/workflows/npm-version-bump.yaml@feature/MM-227-setup-npm-version-bump"
    with:
      runner: '["ubuntu-latest"]'
      version: ${{ inputs.version }}
      branch-creation-condition: ${{ !contains(github.ref, 'v0.') }}
    secrets:
      github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
      github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}
