---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-keycloak-operator
  namespace: flux-system
spec:
  interval: 15m
  path: ./oci/apps/keycloak/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: dummy
  wait: true
